DefaultContentLanguage = "de"
baseURL = "https://fte-13.netlify.app"
copyright = "Everything is mine"
languageCode = "de"
removePathAccents = true
theme = "infinity-hugo"
title = "FTE"
[languages.de]
title = "FTE13 DJ"
weight = 1
[params]
customHead = ""
[params.about]
description = "Ich bin in meiner Freizeit als Entwickler und Designer unterwegs. Im [LXDB](https://web.lxdb.de)-Team arbeite ich an vielen Projekten mit und bin hauptsächlich mit [Arduino](https://www.arduino.cc) beschäftigt."
enable = true
heading = "Über mich"
sliderItem = []
[params.contact]
enable = true
subtitle = "CONTACT Subtitle"
title = "CONTACT Title"
[params.cta]
bg = "/images/lapis.jpg"
enable = true
subtitle = "CTA Subtitle"
title = "CTA Title"
[params.hero]
bg = "/images/img_20200512_205451.jpg"
btnText = "Hero Button"
countdownDay = "31"
countdownMonth = "12"
countdownYear = "2020"
disableCountdown = true
enable = true
subtitle = "Entwickler & Designer"
title = "FTE"
[params.navigation]
about = "Über"
contact = "Kontakt"
home = "Startseite"
logo = "/images/fte.1.png"
service = "Service"
[params.service]
enable = true
subtitle = "SERVICE Subtitle"
title = "SERVICE Title"
[[params.service.serviceItem]]
delay = "0s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-strategy"
title = "Fully Responsive"
[[params.service.serviceItem]]
delay = "0.2s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-circle-compass"
title = "Speed Optimized"
[[params.service.serviceItem]]
delay = "0.4s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-anchor2"
title = "Tons of Feature"
[[params.service.serviceItem]]
delay = "0.6s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-globe"
title = "Fully SEO Optimized"
[[params.service.serviceItem]]
delay = "0.8s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-strategy"
title = "Fully Responsive"
[[params.service.serviceItem]]
delay = "1s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-circle-compass"
title = "Speed Optimized"
[[params.service.serviceItem]]
delay = "1.2s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-anchor2"
title = "Tons of Feature"
[[params.service.serviceItem]]
delay = "1.5s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-globe"
title = "Fully SEO Optimized"
