baseURL = "https://fte-13.netlify.app"
languageCode = "de-de"
removePathAccents = true
theme = "infinity-hugo"
title = ""
[params]
customHead = ""
[params.about]
description = "Text über"
enable = true
heading = "Überschrift über"
[[params.about.sliderItem]]
image = "images/about/1.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[[params.about.sliderItem]]
image = "images/about/3.jpg"
[[params.about.sliderItem]]
image = "images/about/2.jpg"
[params.contact]
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"
title = "Get In Touch"
[params.cta]
bg = "images/call-to-action.jpg"
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"
title = "Subscribe to our mailing list"
[params.hero]
bg = "/images/img_20200512_205451.jpg"
btnText = "Get Started"
countdownDay = "31"
countdownMonth = "12"
countdownYear = "2020"
disableCountdown = false
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna"
title = "BRING YOUR PRODUCT TO LIGHT"
[params.navigation]
about = "Über"
contact = "Kontakt"
home = "Startseite"
logo = "/images/fte.1.png"
service = "Service"
[params.service]
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et"
title = "Find Better Solutions Build Better Products"
[[params.service.serviceItem]]
delay = "0s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-strategy"
title = "Fully Responsive"
[[params.service.serviceItem]]
delay = "0.2s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-circle-compass"
title = "Speed Optimized"
[[params.service.serviceItem]]
delay = "0.4s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-anchor2"
title = "Tons of Feature"
[[params.service.serviceItem]]
delay = "0.6s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-globe"
title = "Fully SEO Optimized"
[[params.service.serviceItem]]
delay = "0.8s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-strategy"
title = "Fully Responsive"
[[params.service.serviceItem]]
delay = "1s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-circle-compass"
title = "Speed Optimized"
[[params.service.serviceItem]]
delay = "1.2s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-anchor2"
title = "Tons of Feature"
[[params.service.serviceItem]]
delay = "1.5s"
description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
icon = "tf-globe"
title = "Fully SEO Optimized"
